/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XjelinekjAmbulanceWlList {
    }
}
declare global {
    interface HTMLXjelinekjAmbulanceWlListElement extends Components.XjelinekjAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXjelinekjAmbulanceWlListElement: {
        prototype: HTMLXjelinekjAmbulanceWlListElement;
        new (): HTMLXjelinekjAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xjelinekj-ambulance-wl-list": HTMLXjelinekjAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XjelinekjAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xjelinekj-ambulance-wl-list": XjelinekjAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xjelinekj-ambulance-wl-list": LocalJSX.IntrinsicElements["xjelinekj-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXjelinekjAmbulanceWlListElement>;
        }
    }
}
